name: EgyptOnline CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Login to DockerHub
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build image
    - name: Build image
      run: |
        docker build --no-cache -t bodeayman/egyptonlinema3ak-backend:latest .

    # Tag image
    - name: Tag image
      run: |
        docker tag bodeayman/egyptonlinema3ak-backend:latest bodeayman/egypt_online_ma3ak:latest

    # Push image
    - name: Push image
      run: |
        docker push bodeayman/egypt_online_ma3ak:latest

    # SSH to VPS and deploy
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/egyptonlinema3ak
          sudo ./deploy.sh
    - name: Health check
      run: |
        sleep 15
        curl -f https://egyptonlinema3ak.com/health
    
    - name: Run all tests
      run: dotnet test EgyptOnline/EgyptOnline.csproj --configuration Release --logger "console;verbosity=normal"
    
    - name: Run login tests specifically
      run: dotnet test EgyptOnline/EgyptOnline.csproj --filter "FullyQualifiedName~UserLoginServiceTests" --configuration Release
